ndk: Add test feature to enable ndk-sys/test
Fixes the following failure when compiling on a host that's not android:

    error: android-ndk-sys only supports compiling for Android
      --> ndk-sys/src/lib.rs:18:1
       |
    18 | compile_error!("android-ndk-sys only supports compiling for Android");
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In addition jni and jni-glue need to be linked to prevent subsequent
failures when compiling the documentation in native_activity.rs.