ci: Remove --target rustdoc from ndk tests
This feature does not exist anymore and breaks the tests:

    error: Package `ndk v0.2.1 (/home/runner/work/android-ndk-rs/android-ndk-rs/ndk)` does not have these features: `rustdoc`

Fixes: 7d36455 ("Explicitly set docs.rs targets and bump versions to 0.2.1/0.5.3 (#82)")