ndk-sys: Regenerate against NDK r25.0 (build 8775105) (#324)
* ndk-sys: Regenerate against NDK r25.0 (build 8775105)

Note that an `enum` suffix had to be added to `AMidi.h` to prevent
`bindgen` from erroring out on:

    ~/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/linux-x86_64/sysroot//usr/include/amidi/AMidi.h:230:1: error: must use 'enum' tag to refer to type 'AMidiDevice_Protocol'
    ~/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/linux-x86_64/sysroot//usr/include/amidi/AMidi.h:230:1: error: must use 'enum' tag to refer to type 'AMidiDevice_Protocol', err: true
    thread 'main' panicked at 'Unable to generate bindings: ()', src/main.rs:52:36
    stack backtrace:
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Also list this NDK version in the `ndk-sys` version metadata, exposing
it on the crates.io frontpage.

* bitmap: Add new `RGBA_1010102` constant since NDK r25.0