ndk-macro: Reexport android_logger from ndk-glue and use it in macros
When enabling the logger feature:

    error[E0433]: failed to resolve: use of undeclared type or module `android_logger`
     --> ndk-examples/examples/hello_world.rs:6:5
      |
    6 |     ndk_glue::main(backtrace = "on", logger(level = "debug", tag = "hello-world"))
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type or module `android_logger`
      |
      = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

This means the crate user is responsible for importing the
android_logger crate in their namespace where this macro is used.  That
is not ideal, especially when ndk-glue already imports it but doesn't
seem to use it anywhere.